### PR TITLE
Update for Idris 1.2

### PR DESCRIPTION
**Pull request by clayrat**
Fixes https://github.com/jameshaydon/smproc/issues/1

### CODE REVIEW

**Review by jameshaydon — APPROVED** [review]
nice!

**Comment by clayrat** [comment]
Great :) Do you have further plans for this? I guess TODO in the readme outlines next steps?

**Comment by jameshaydon** [comment]
I don't know, I may want to port this to use the elixir code-generator, in
particular it might be really nice to compile these to Elixir GenStages (
https://elixir-lang.org/blog/2016/07/14/announcing-genstage/). Since this
model doesn't allow the topology to change, it seems suited for setting up
large-scale systems. Or maybe something like:
https://github.com/antonmi/flowex.

Then again maybe https://github.com/jameshaydon/cospanProc is more
practical (I'm thinking of replacing CSP/pi-calc with just Actors), I'm not
really sure yet. I'd like to make an abstract framework for architecting
large distributed applications in Idris (using category theory to organise
it) but I'm still not sure what the right way to do that is :)

Let me know if you have ideas!

**Comment by clayrat** [comment]
My current pet project is trying to figure out some common graphical formalism for linear algebra, linear types and concurrency, so it seems that symmetric monoidal categories are a close fit. Do I understand correctly that (due to the use of duals & cups/caps) you're actually using traced SMC here?

**Comment by jameshaydon** [comment]
I think that's true yes.

**Pull request merged**
